version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kaiten-spring-app
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=config.toml